### ISSUE TITLE
Improve error plugin handling 

### ISSUE THREAD

**Issue by m00g3n** [kyma-incubator/kitbag#10]
**Description**

Enhance error handling mechanism by wrapping plugin's execution error messages with [fail](https://github.com/kyma-incubator/kitbag/blob/main/lib/utils.sh#L36) method. 

**Reasons**

- to delegate error handling to framework and simplify plugin development

**Comment by tobiscr** [comment]
Kitbag is descoped from Kyma. Closing all issues.
