### ISSUE TITLE
Investigate the way of installing/uninstalling new plugins

### ISSUE THREAD

**Issue by m00g3n** [kyma-incubator/kitbag#12]
**Description**

ATM the plugin installation is reduced to placing the plugin's file into the `plugin` directory.  
There is no mechanism (or guide) to install/uninstall all the plugin's dependency binaries.

Investigate and propose  plugin's formal installation/uninstallation in kitbag. 

**Reasons**

- will help in kitbag's adoption
- improves kitbag's ergonomic

**Comment by tobiscr** [comment]
Kitbag is descoped from Kyma. Closing all issues.
