### ISSUE TITLE
Add support for array arguments

### ISSUE THREAD

**Issue by m00g3n** [kyma-incubator/kitbag#6]
**Description**

Add support for array arguments.

```bash
$ kitbag plugin test -array 1st,2nd,3rd
``` 

**Reasons**

Array arguments handling should not be implemented in plugin scope. 

**Attachments**

example [implementation](https://github.com/kyma-incubator/kitbag/pull/2/files#diff-6b07ce1aed2389cd718a101273e55faaf81fd757a3252b0c584a1c19d684c8c8R51)

**Comment by tobiscr** [comment]
Kitbag got descoped from Kyma scope. Closing this issue
