### ISSUE TITLE
Investigate a mechanism to detect deviations from the kitbag's convention in plugin scripts

### ISSUE THREAD

**Issue by m00g3n** [kyma-incubator/kitbag#8]
**Description**

Kitbag is following the [convention over configuration](https://github.com/kyma-incubator/kitbag#31-convention-over-configuration) principle. We should investigate mechanisms that would help us detect the deviations from the kitbag's convention (e.g. the variable naming) in plugin scripts.

**Reasons**

- to improve development experience
- to improve the quality of the code by eliminating errors in early stage (e.g. variable name overlaping)
- to speed up code review

**Comment by tobiscr** [comment]
Kitbag got descoped from Kyma deliverables... closing this issue
